import type { Maze } from '../lib/generate_maze'
import { BLOCKS } from "../lib/blocks";

const PRESET_1: Maze = [
    new Array(15).fill(BLOCKS.BLOCK_VOID),
    [BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_GOAL, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID],
    [BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_CACTUS, BLOCKS.BLOCK_VOID],
    [BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_CACTUS, BLOCKS.BLOCK_VOID],
    [BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_CACTUS, BLOCKS.BLOCK_VOID],
    [BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_MAGMA, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_CACTUS, BLOCKS.BLOCK_VOID],
    [BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_CACTUS, BLOCKS.BLOCK_VOID],
    [BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_HONEY, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_CACTUS, BLOCKS.BLOCK_VOID],
    [BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_WATER, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_MAGMA, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_CACTUS, BLOCKS.BLOCK_VOID],
    [BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_START, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_PATH, BLOCKS.BLOCK_VOID, BLOCKS.BLOCK_VOID],
    new Array(15).fill(BLOCKS.BLOCK_VOID)
]

export const PRESETS = [
    PRESET_1
]